Add geometry buffers to renderable objects
chanzuckerberg/idetik pull request #45
Opened 2024-09-18 20:12 UTC by shlomnissan

### Summary

This PR implements several refactoring tasks discussed in previous
conversations:

- It replaces the "mesh source" type with a geometry type that stores all
vertex data in a single buffer.
- It attaches geometry to every renderable object.
- It introduces a node type for generating unique IDs for non-renderable
objects such as geometry and textures.

### Notes

Before moving on from refactoring, I have a couple of quick follow-ups to address:
1. Disposing of geometry and texture data from the GPU
2. Adding a simple logger class

### Related Issue
Closes #24 

### Tests & Checks

- Manual verification. Everything works as expected.

2024-09-18 21:42 UTC, shlomnissan commented on src/objects/geometry/plane_geometry.ts
> +    const index: number[] = [];
I could likely pre-calculate the vertex and index sizes and write them directly to the buffers, rather than storing the data in intermediate number arrays. However, I don't consider pressing at the moment.

2024-09-18 21:43 UTC, shlomnissan commented on src/renderers/webgl_bindings.ts
> +      if (attr.type === "uv") idx = 2;
We may want this mapping to be defined elsewhere, or to be more flexible, perhaps by adding an index to the geometry attribute data structure.

2024-09-19 12:15 UTC, andy-sweet approved these changes
Definitely an improvement over `MeshSource`, so looks good to me. Would be nice to have more explicit structure for the interleaved attributes, but that's not blocking and I don't have immediate suggestions.

2024-09-19 12:15 UTC, andy-sweet commented on src/core/geometry.ts
> +  protected indexData_: Uint32Array = new Uint32Array();
Nit: the default values of these members are always clobbered in the constructor, so remove the assignments?

```suggestion
  protected vertexData_: Float32Array;
  protected indexData_: Uint32Array;
```

2024-09-19 12:15 UTC, andy-sweet commented on src/renderers/webgl_bindings.ts
> +      if (attr.type === "uv") idx = 2;
Agreed it would be good to improve this in the future, especially because the order of these interleaved values is also needed when populating `Geometry.vertexData_`.

2024-09-19 12:15 UTC, andy-sweet commented on src/renderers/webgl_bindings.ts
> +      if (attr.type === "uv") idx = 2;
Also, should we have some kind of explicit exhaustive check here for `attr.type`, or is that being handled well enough by standard TypeScript checks?

2024-09-19 15:41 UTC, aganders3 requested changes
I agree this is definitely an improvement!

I have some concerns that need to be ironed out to marry this with my PR #46 that introduces a new renderable object, but I'm happy to make the needed changes on that PR (or an intermediate one). So I'm happy to approve this in spirit, but I think there are a few changes that should be made or captured as issues.

My main thought here is that renderable objects are strongly (and I think necessarily?) coupled to their shaders. They likely all need different attributes (and orders) and uniforms. This means the object could be aware of its own program (obviating `WebGLRenderer.getProgramName`).

To me this also means `Geometry` should not restrict the available attributes. I think that's basically what you're getting at with this thread: https://github.com/chanzuckerberg/imaging-active-learning/pull/45#discussion_r1765759351.

I don't have a great idea of _where_ this info should live though. My first thought is that it belongs on the renderable object itself, which could provide `getAttributes` and `getUniforms` for example. I guess this turns the `Geometry` class into more of a utility class to make it easier to pack data into an interleaved buffer and bookkeep the stride + offsets.

2024-09-19 15:41 UTC, aganders3 commented on src/renderers/webgl_renderer.ts
> +    this.bindings_.bind(object);
naming nit: seeing this next to `this.textures_.bind()` makes me think "bindings_" and "WebGLBindings" may not be the right name. Maybe `WebGLBuffers` or something?

2024-09-19 15:41 UTC, aganders3 commented on src/renderers/webgl_renderer.ts
>      }
Can we avoid checking the object type here? Other renderable objects might have textures as well so it seems like it should be okay.

Also as a future thought - some renderable objects may need multiple textures so `WebGLTextures.bind()` could take a list of them (which may be empty). That would get rid of the conditional here entirely.

2024-09-19 15:41 UTC, aganders3 commented on src/renderers/webgl_renderer.ts
> +    return DEFAULT_PROGRAM;
Does it make sense to have a default program if the object type is not recognized? Maybe this should throw instead.

2024-09-19 15:41 UTC, aganders3 commented on src/objects/geometry/plane_geometry.ts
> -        this.uvs_.push(u, v);
nit: I think you can remove these comments and replace `vertex.push(0, 0, 1)` with

```
const normal = [0, 0, 1];
vertex.push(...normal);
```

You could do the same for position but that's pretty clear here.

2024-09-19 15:41 UTC, aganders3 commented on src/core/geometry.ts
> +  protected indexData_: Uint32Array = new Uint32Array();
This is more than a nit I think. An empty typed array is truthy, so I think having this affects the checks on `if (indexData)` (in `WebGLBindings.bind` and `WebGLRenderer.renderObject`).

2024-09-19 15:41 UTC, aganders3 commented on src/renderers/webgl_bindings.ts
> +        attr.offset * Float32Array.BYTES_PER_ELEMENT
This can go into future work, but right now this prevents mixing data types in the interleaved buffer. Could `stride` and `offset` return bytes instead of counts?

2024-09-19 15:41 UTC, aganders3 commented on src/objects/geometry/plane_geometry.ts
From prior discussion I thought the intent was to _not_ use `Geometry` as a base class. Could this instead be a function that returns a `Geometry` object?

2024-09-20 18:16 UTC, aganders3 approved these changes
I'm preemptively approving after our discussion today so my time zone does not become a blocker. Feel free to merge when ready!

2024-09-20 19:52 UTC, shlomnissan commented on src/objects/geometry/plane_geometry.ts
We discussed and agreed that it's acceptable for the plane geometry object to inherit directly from the Geometry object. However, we remain open to changing this structure if needed.

2024-09-20 19:57 UTC, merged