Add a React + SDS ultrack prototype
chanzuckerberg/idetik pull request #49
Opened 2024-09-19 21:44 UTC by andy-sweet

### Summary

This adds a React + SDS prototype application to `ultrack-prototype/frontend` that uses the visualization package to render some OME-Zarr image data.

<img width="812" alt="Screenshot 2024-09-19 at 11 08 53 AM" src="https://github.com/user-attachments/assets/b2537b13-4d39-4886-b5b4-86c036f44a1f">

To keep things simple and small, I just added enough to exercise the visualization library in addition to some playback controls (borrowed from https://github.com/royerlab/points-web-viewer), so that it forms a very early skeleton for the prototype app.

The playback controls are interactive, but have no meaninful side-effects on visualization yet. For this to be functional, we need to at least allow the `ImageLayer` to load new texture data based on the current time point. This requires a few changes (e.g. https://github.com/chanzuckerberg/imaging-active-learning/issues/33), and is generally a good driver of the library's early API design and functionality.

As this is currently a prototype for developers, React and SDS are dev dependencies. You can serve the prototype by running

```shell
npm run dev -- --mode prototype
```

### Related Issue
Closes #27

### Tests & Checks
I manually tested the application by running the command above.

2024-09-20 12:32 UTC, andy-sweet commented on src/renderers/webgl_renderer.ts
> +    this.gl.clearColor(0, 0, 0, 1.0);
I made the background color of the canvas black as a better presentation for the prototype. This should probably be configurable at some point, but black seems like a reasonable default for scientific images.

2024-09-20 12:34 UTC, andy-sweet commented on ultrack-prototype/frontend/components/App.tsx
> +const layerManager = new LayerManager();
I put the source, layer, and layer manager in this file because I think some version of them must sit at this level of the component hierarchy so that the playback controls can be updated with the layer's relevant metadata after opening (e.g. number of time points), and so that the playback controls can modify the region to load.

These are not functional yet, so I could move these into the renderer component for now to remove the need for renderer props.

2024-09-20 18:19 UTC, aganders3 approved these changes
LGTM, thanks!

I was able to pull and run this branch with just:
```
npm install
npm run dev -- --mode prototype
```

2024-09-20 18:22 UTC, aganders3 commented on src/renderers/webgl_renderer.ts
> +    this.gl.clearColor(0, 0, 0, 1.0);
I agree it should be configurable at some point. I think having it non-black can help while debugging because you can see the edges of the image, but I am okay with this change.

2024-09-20 20:20 UTC, shlomnissan commented on src/renderers/webgl_renderer.ts
> +    this.gl.clearColor(0, 0, 0, 1.0);
Yep, I think making it a property of the generalized Renderer class is a sensible approach.

2024-09-23 16:43 UTC, shlomnissan requested changes
Overall, I think this PR looks good.

I’m going to request changes because I believe there are opportunities to improve the composition of the components—specifically, moving objects and some state out of `App.tsx` and into the relevant components.

I also have questions about how we update regions and why we need to store this information in the renderer or layer manager. However, this isn't directly related; we can discuss it in our next engineering sync.

2024-09-23 16:43 UTC, shlomnissan commented on tsconfig.json
> +  "include": ["examples", "src", "test", "ultrack-prototype/frontend"]
Nit: I think a more common directory name combinations would be `app` and `server`, or `client` and `server`.

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/App.tsx
> +    // with React state that captures the time-point.
I raised this question in Issue #33, but why do we want the region to be associated with the renderer or the layer manager instead of the data source (which might be managed through a specialized layer)?

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/App.tsx
> +const layerManager = new LayerManager();
Why not encapsulate all viewer-related code in a single component and manage state at this level to coordinate updates between UI components and the viewer?

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/App.tsx
> +  const [numTimes, _] = useState<number>(791);
```suggestion
  const [numTimes] = useState<number>(791);
```

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/App.tsx
> +  }, [numTimes, curTime, playing]);
I think all this logic can be encapsulated within the `PlaybackControls` component. If you need to pass data back to the viewer through this component, you can provide callbacks to the playback component. Something along the lines of:
```
const onTimeChange = (currTime: number) => {}
const onPlayToggle = (isPlaying: boolean) = {}
```

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/Main.tsx
> +import { StyledEngineProvider, ThemeProvider } from "@mui/material/styles";
Is this part of SDS's recommended modules for theme management? I'd expect SDS to provide some kind of internal theme provider. I have the same question about `<Box>` — I would have assumed that SDS would offer a grid system, or at least fixed measurements to ensure consistency in gaps and margins.stent.

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +    setCurTime: (curTime: number) => void;
This comment builds on my earlier point. The callbacks here seem reversed. Passing mutators down to a child component can break encapsulation. Typically, it's better for a child component to notify the parent of events via callbacks, allowing the parent to handle state updates:
- The child modifies the parent's state, leading to tight coupling and making reuse harder.
- The parent should manage state; passing mutators down mixes responsibilities.
- Direct state manipulation by the child complicates testing, debugging, and reasoning.

2024-09-23 16:43 UTC, shlomnissan commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +                id="time-frame-slider"
Why is it necessary to specify an ID in this case?

2024-09-23 16:43 UTC, shlomnissan commented on vite.config.js
> +  return undefined;
Nit: I don't see much value in returning undefined and would have defaulted to examples.

2024-09-23 18:57 UTC, andy-sweet commented on src/renderers/webgl_renderer.ts
> +    this.gl.clearColor(0, 0, 0, 1.0);
I created an issue here: https://github.com/chanzuckerberg/imaging-active-learning/issues/52

2024-09-23 19:00 UTC, andy-sweet commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +                id="time-frame-slider"
Not necessary. Removed.

2024-09-23 19:07 UTC, andy-sweet commented on vite.config.js
> +  return undefined;
Don't feel too strongly, but I was assuming that `undefined` (as was returned before this PR in a similar case) would not serve successfully, which seemed like desirable behavior if an unrecognized mode was passed (e.g. due to a typo). It is not served successfully, but there is no indication (server or client side) of that failure (other than a 404 for the client). What about using `console.error` here and continuing to return `undefined`?

2024-09-23 19:13 UTC, andy-sweet commented on ultrack-prototype/frontend/components/App.tsx
> +const layerManager = new LayerManager();
I'm not sure I can give a better explanation that the first comment.

To clarify, for the functionality of this PR, I can push these and related state/effects further down into only the components they affect. I will do that to keep this PR as simple as possible. But I suspect they will be lifted up soon in some form.

2024-09-23 19:48 UTC, andy-sweet commented on ultrack-prototype/frontend/components/App.tsx
> +    // with React state that captures the time-point.
I left a more detailed comment on #33. The short summary is that I think the region here defines the sub-region that we want to present across all layers. Each layer and its loader should use its metadata to map that sub-region to the dimensions/regions associated with its underlying data, then fetch and populate vertices/textures accordingly

2024-09-23 19:51 UTC, andy-sweet commented on ultrack-prototype/frontend/components/App.tsx
> +  }, [numTimes, curTime, playing]);
I think that `curTime` is an example of state that will need to be shared between the slider and whatever is responsible for triggering a load of the corresponding data at that time.

But that is not the case right now because the app doesn't do anything interesting, so your point holds - we can just push this all into `PlaybackControls` so I'll do that for now.

2024-09-23 20:00 UTC, andy-sweet commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +    setCurTime: (curTime: number) => void;
Sorry, I think the points here mostly stem from anticipating functionality that will shortly be in the application, but is not currently (i.e. `curTime` is currently more boring that it will be soon).

I am assuming that `curTime` will be state that is shared across multiple components, in which case I believe the recommended design pattern in React is to lift that state up into the parent component and pass the dispatchers (or functions that call them) down in to the children: https://react.dev/learn/sharing-state-between-components

Not sure I understand the point about callbacks though - that's how I would describe the dispatchers like `setCurTime`. They are callbacks for the React state machine to work out what to do with the state change (e.g. re-render). From what I understand of React, I would not describe them as mutators

2024-09-23 20:07 UTC, andy-sweet commented on ultrack-prototype/frontend/components/Main.tsx
> +import { StyledEngineProvider, ThemeProvider } from "@mui/material/styles";
I copied this straight from Ashley's work on the zebrahub viz tool, but using the material provider is consistent with the SDS examples (e.g. see `index.tsx` in the first example): https://sds.czi.design/009eaf17b/p/169911-theming/b/36245e

The next line imports an SDS theme (the default one), which is used below.

I can't find any SDS-specific layouts/grids in the [SDS docs](https://sds.czi.design/009eaf17b/p/55ad7a-introduction), but maybe I just didn't look hard enough yet.

2024-09-23 20:09 UTC, andy-sweet commented on tsconfig.json
> +  "include": ["examples", "src", "test", "ultrack-prototype/frontend"]
I'm going to leave this now since this matches the prototype architecture diagram and it's a nit. Feel free to change later.

2024-09-23 21:26 UTC, shlomnissan approved these changes
I left a couple of suggestions, but otherwise, LGTM

2024-09-23 21:26 UTC, shlomnissan commented on ultrack-prototype/frontend/components/App.tsx
> +      <PlaybackControls></PlaybackControls>
As we discussed during our Zoom call, we'll need to manage shared state in this component. However, this doesn't necessarily mean the top-level component should handle state directly related to its children. When defining the child components, we should consider their internal scope and their public interface carefully. For the public interface, it makes sense, for example, to pass the URL to the renderer component or the playback FPS to the playback component. I do consider this configuration “speculative” at this point, but they are sensible enough that it’s probably okay.

2024-09-23 21:26 UTC, shlomnissan commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +  const [playing, setPlaying] = useState<boolean>(false);
TypeScript should be able to deduce the underlying type based on the value passed to `useState`.

```suggestion
  const [curTime, setCurTime] = useState(0);
  const [playing, setPlaying] = useState(false);
```

2024-09-23 21:26 UTC, shlomnissan commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +  }, [numTimes, curTime, playing]);
- I haven't tested this, but I think using `curTime + 1` directly can lead to stale closures because `curTime` may not be the latest state when the interval runs. Instead, you can use a functional update for `setCurTime` to always get the latest value of `curTime`.
- Nit: The return statement can be simplified.
```suggestion
  useEffect(() => {
    console.debug("effect-playback: ", curTime, playing);
    if (playing) {
      const interval = setInterval(() => {
        setCurTime((prevCurTime) => (prevCurTime + 1) % numTimes);
      }, playbackIntervalMs);
      return () => clearInterval(interval);
    }
  }, [numTimes, curTime, playing]);
```

2024-09-24 13:41 UTC, andy-sweet commented on ultrack-prototype/frontend/components/PlaybackControls.tsx
> +  }, [numTimes, curTime, playing]);
I was unaware of this form - thanks!

The other improvement (in addition to potential stale-ness) this has is that the effect is no longer explicitly dependent on `curTime` (other than the debug log, which can be removed), so it will only re-run when playing changes which seems like the right approach with set/clearInterval. Before, the effect would re-run on every change to `curTime` so the interval was never really being used in the happy path of the event loop keeping up (i.e. set/clearTimeout would be more suitable).

I made this change myself to remove `curTime` from the dependency list and to clean up the arrow function formatting a little more

2024-09-24 17:31 UTC, merged