Add orthographic camera and a simple transform
chanzuckerberg/idetik pull request #57
Opened 2024-09-25 21:28 UTC by shlomnissan

### Summary

This PR introduces an orthographic camera and a basic transform for all
renderable objects. While the transform is currently incomplete,
I've put this together this to test the orthographic camera and
illustrate my intended approach.

### Related Issue
Closes #23 

### Tests & Checks

Visual confirmation that the transform and camera function as intended. See screenshot below.

![Screenshot 2024-09-25 at 2 27 36 PM](https://github.com/user-attachments/assets/55281e16-6c08-4022-b94c-9076155121e0)

2024-09-25 21:29 UTC, shlomnissan commented on src/core/renderer.ts
> +      if (this.activeCamera_ instanceof OrthographicCamera) {
I know we don’t like this, but I'll maintain this pattern for now until we devise a better solution for managing camera responses to viewport dimension changes.

2024-09-26 15:38 UTC, andy-sweet requested changes
Mostly lots of comments, questions, and nits.

The only requested change is to explain or fix the comment about the call to `super()` in `OrthographicCamera`, which isn't entirely new as `PerspectiveCamera` does something similar.

I think it might also be worth implementing support for scale and rotation to better understand the implementation of `Transform`, but we can also do that when needed.

2024-09-26 15:38 UTC, andy-sweet commented on src/core/transform.ts
> +export class Transform {
The exported name `Transform` is vague and as a client of a class like this, I'd hope for the name to be more specific and descriptive (e.g. `AffineTransform`, `MatrixTransform`, `ProjectiveTransform`). Based on the follow-up work described in the TODOs, I think we can avoid a rename for now though.

2024-09-26 15:38 UTC, andy-sweet commented on src/core/renderer.ts
> +      if (this.activeCamera_ instanceof OrthographicCamera) {
Seems fine for now.

2024-09-26 15:38 UTC, andy-sweet commented on src/core/transform.ts
> +  public translate(axis: vec3, distance: number) {
Optional

Not too important, but given my expectations of what `Transform.translate` would do and our current usage of it, I would just use a single argument here which is the translation vector (instead of the unit vector and the scale). That also avoids the need for the client to understand the position of arguments and an extra function call.

2024-09-26 15:38 UTC, andy-sweet commented on src/core/transform.ts
> +  private position_ = vec3.create();
Nit: I don't think of transforms having positions, so I'd prefer `translation_` or similar here.

```suggestion
  private translation_ = vec3.create();
```

2024-09-26 15:38 UTC, andy-sweet commented on src/core/transform.ts
> +    this.dirty_ = true;
With only translation, the dirty pattern is unnecessarily complex - you could just call `mat4.translate` with the existing `mat4` instance assigned to `this.matrix_`. But I assume it's here to support composing other parameters in some order (e.g. scale, rotation), right?

2024-09-26 15:38 UTC, andy-sweet commented on src/objects/cameras/camera.ts
> +    return this.transform.matrix;
It's confusing to have both `Camera.transform` (that returns a `Transform`) and `Camera.viewTransform` (that returns a `mat4`) when they both contain the same information.

Why not just remove `viewTransform` and have the client deal with accessing the `mat4` through the `matrix` property getter when they need it?

For consistency, I might also expect `projectionTransform` to return a `Transform` now that we have it.

2024-09-26 15:38 UTC, andy-sweet commented on src/objects/cameras/orthographic_camera.ts
> +    super();
This call to `Camera`'s constructor will call `updateProjectionTransform` when `this.left_` (and similar values) are undefined. Is that safe? Is it desirable? If not, I'd be fine with just removing the call in the `Camera` constructor and force the non-abstract classes to populate `projectionTransform_` appropriately. Or maybe there's a way to use similar dirty flag logic as in the `Transform` implementation.

2024-09-26 17:47 UTC, shlomnissan commented on src/objects/cameras/orthographic_camera.ts
> +    super();
Good catch! I hadn't realized I was calling it in the `Camera` class. I'll remove the call from the `Camera` class for now. Having a base class invoke an abstract function defined in a derived class seems like a bad design choice anyway.

2024-09-26 17:52 UTC, shlomnissan commented on src/core/transform.ts
> +export class Transform {
I'll rename it to `AffineTransformas`. I agree it's more descriptive.

2024-09-26 17:55 UTC, shlomnissan commented on src/core/transform.ts
> +  public translate(axis: vec3, distance: number) {
I'm fine incorporating your suggestion. In previous implementations, I maintained generic transformation functions while introducing axis-aligned transformations (such as rotateX, rotateY, etc.) at a higher level when necessary, but I don’t think it’s necessary at this point.

2024-09-26 17:58 UTC, shlomnissan commented on src/core/transform.ts
> +  private position_ = vec3.create();
This naming convention aligns with engines and renderers I'm familiar with (like Three.js and Godot, Ogre3D). However, I don't have a strong preference here. Your suggestion seems reasonable, so I'll implement the change.

2024-09-26 18:08 UTC, shlomnissan commented on src/core/transform.ts
> +    this.dirty_ = true;
The current approach is particularly valuable in the context of a scene graph, where multiple translations occur as transformations propagate through the graph. In such cases, performing matrix multiplication once (if at all) is beneficial. It's still applicable to our scenario, as you might want to apply multiple translations in a single rendering iteration.

My proposed idea involves introducing a vector to represent scale and a quaternion to represent the current orientation. If the dirty flag is set, we can assemble the transformation matrix inline, rather than using utility functions like `mat4.translate`, `mat4.scale`, etc., however, this using helper functions is probably fine as an intermediate state.

I'm inclined to leave it as is, unless you have strong feelings about it. I don't find it overly complex, and I don't think it's a crucial issue at this stage. However, I'm open to changing it.

2024-09-26 18:15 UTC, shlomnissan commented on src/objects/cameras/camera.ts
> +    return this.transform.matrix;
- Another option is to change the visibility of the transform accessor to protected and let the underlying rendering object define how the object can be transformed. Either way, I agree it's confusing. I'll remove `viewTransform` for now.
- I'm unsure about converting the projection matrix to an affine transform object. This conversion might not be necessary, as I don't anticipate modifying it without considering the camera's parameters. However, I'm willing to make this change if it addresses an active use case. In the meantime, I'll rename `projectionTransform` to `projectionMatrix` to clarify that it doesn't return an affine transform object. Does this approach sound okay to you?

2024-09-26 19:53 UTC, shlomnissan commented
> I think it might also be worth implementing support for scale and rotation to better understand the implementation of Transform, but we can also do that when needed.

@andy-sweet I agree, this will be a quick follow-up. My initial goal was to implement an orthographic camera in this PR, but the transform was necessary for easy testing. I'll continue working on it in a subsequent PR.

2024-09-26 23:10 UTC, andy-sweet commented on src/objects/cameras/camera.ts
> +    return this.transform.matrix;
Removing `viewTransform` and renaming to `projectionMatrix` sounds good to me!

2024-09-26 23:13 UTC, andy-sweet approved these changes
Looks good to me now.

2024-09-26 23:13 UTC, andy-sweet commented on src/objects/cameras/camera.ts
>    constructor() {
Nit: after the removal of `this.updateProjectionTransform()`, I'm assuming javascript gives us this constructor as the default constructor, so this can also be removed?

2024-09-27 01:47 UTC, aganders3 approved these changes
Looks good, thanks! This will be really useful for playing with the sample data.

I think Cameras and Transforms could probably be more closely related later. It seems like you started down that road here and backed it out, so I'm fine with keeping them separate for now.

2024-09-27 01:47 UTC, aganders3 commented on src/renderers/webgl_renderer.ts
> +    );
Since this is not GL-specific code I feel like it _might_ belong in the parent class `render` method. Not blocking, just something to think about later.

2024-09-27 01:47 UTC, aganders3 commented on src/objects/cameras/camera.ts
>    protected abstract updateProjectionTransform(): void;
nit: with `projectionTransform` renamed `projectionMatrix` this could be renamed `updateProjectionMatrix` as well.

2024-09-27 01:47 UTC, aganders3 commented on src/core/renderer.ts
> +      if (this.activeCamera_ instanceof OrthographicCamera) {
Yeah I don't think the general pattern needs to change here, but I'm still in favor of changing it!

If I were going to change anything here I'd center the orthographic frame on (0, 0), as I think that's how the perspective camera works.

2024-09-27 15:31 UTC, shlomnissan commented
> I think Cameras and Transforms could probably be more closely related later. It seems like you started down that road here and backed it out, so I'm fine with keeping them separate for now.

@aganders3  Could you clarify what you mean by "closely related"? Is there a specific aspect or feature you think is missing from the current relationship between Cameras and Transforms?

2024-09-27 15:36 UTC, shlomnissan commented on src/renderers/webgl_renderer.ts
> +    );
That's a good point. I will leave it as is for now. I like the fact that it's an abstract method and that all the code is in one place, but we could reconsider when we introduce a new experimental renderer.

2024-09-27 16:05 UTC, aganders3 commented
Sorry, it was just poorly worded. What I meant was right now we have objects that can have an `AffineTransform` (our code) and cameras that use `gl-matrix` operations to store transforms as `mat4`. If we have our own library of transforms (even if they're mostly just wrapping `gl-matrix` operations) it makes sense to me to use them in the Cameras as well.

2024-09-27 17:06 UTC, shlomnissan commented on src/core/renderer.ts
> +      if (this.activeCamera_ instanceof OrthographicCamera) {
That's a good point! I centered the orthographic plane on `(0, 0)`.

2024-09-27 17:09 UTC, merged