Add pan + zoom for orthographic and perspective cameras
chanzuckerberg/idetik pull request #96
Opened 2024-10-23 17:52 UTC by aganders3

### Summary
As discussed each camera has two transformation matrices that ultimately just get composed. This also stores zoom separately and applies it when updating the projection matrix. For the `OrthographicCamera` it keeps the frame centered (0, 0) and pans by setting translation on the `camera.transform`, so I updated it to store just width and height.

I moved the camera controls to their own class in https://github.com/chanzuckerberg/imaging-active-learning/commit/2f7f7e6a5d579701fed8c4bc00095cdf88136c7d. This has some oddities as we discussed yesterday, mostly due to render.canvas being private and the "active" camera switching. I am open to reverting that (keeping the callbacks in the example for demo purposes) for to keep the PR a bit less intrusive.

It's an open question how to get the clip-space Z value for the object - necessary for natural panning with the `PerspectiveCamera`. Right now I calculate this in the client and just assume the object is at Z = 0 in world space (and that the camera is looking along Z). Ultimately picking or some other parameter (i.e. giving a world-space plane) might be a better solution.

### Related Issue
Related to #89 (but does not close)
Closes #101 

### Tests & Checks
Tested manually by adding pan/zoom mouse controls and a camera toggle to the `image2d_from_omezarr5d_u8` example.

https://github.com/user-attachments/assets/9a21c836-7039-48e9-9948-1e9b7bee4fbc

2024-10-24 14:54 UTC, andy-sweet commented on src/objects/cameras/orthographic_camera.ts
> +  // TODO: store width and height instead?
I'm in favor because it makes this camera more consistent with `PerspectiveCamera` and it also removes the confusion about top/bottom when/if we choose to use a coordinate system where (0, 1, 0) points down.

2024-10-24 15:05 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +    const fov = Math.max(0.1, Math.min(179.9, this.fov_ / this.zoom_));
It's a little weird that the clamping happens here and not when setting zoom or field-of-view.

Regardless, it probably makes sense to define an effective fov so the client has access to this information too.

2024-10-24 15:16 UTC, andy-sweet commented on examples/image2d_from_omezarr5d_u8/main.ts
> +perspectiveCam.transform.translate(cameraPos);
It would be ideal to add a `position` argument that defaults to `(0, 0, 0)`.

Especially nice if we use structured keyword arguments for the camera constructors.

2024-10-24 15:25 UTC, andy-sweet commented on examples/image2d_from_omezarr5d_u8/main.ts
> +document.addEventListener("wheel", (event) => {
At a minimum, it would be nice to move some of these callbacks and functions to a separate lib/helper module to help keep the example relatively concise and readable. But agreed with the PR description sentiment, that some/most of these belong in the visualization library as helpers.

2024-10-24 17:14 UTC, andy-sweet commented on examples/image2d_from_omezarr5d_u8/main.ts
> +  const width = camera.type == "PerspectiveCamera" ? 20 : 0.01;
Why does the width need to be different for each camera? Is that due to the way the projected line's shader program? Or is there a simpler explanation?

Without this need, you would need to recreate the `AxesLayer` and reset the layers right? Alternatively, we could just add a setter for `AxesLayer.width`.

2024-10-25 01:51 UTC, aganders3 commented on examples/image2d_from_omezarr5d_u8/main.ts
> +  const width = camera.type == "PerspectiveCamera" ? 20 : 0.01;
Good catch - I had written this off as the line shrinking as it got farther from the camera (the PerspectiveCamera is much farther from the line) but that doesn't make sense because the line is projected in screen space.

I think it's a bug in the line shader and the offset needs to be multiplied by `currPos.w`. It's a tiny fix so I'll make an issue and fix here if that's okay with you.

2024-11-04 15:12 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +    const fov = Math.max(0.1, Math.min(179.9, this.fov_ / this.zoom_));
The clamping is here such that we don't have to override the `zoom` setter from the base class, and right now FOV is private. But I agree this is weird. It's kind of weird to keep track of both FOV and zoom separately given they have the same effect.

I'll give it some thought but suggestions are welcome.

I like the idea of an effective FOV property.

2024-11-04 15:14 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +    const fov = Math.max(0.1, Math.min(179.9, this.fov_ / this.zoom_));
I think this also means adding a "effective" width and height properties to `OrthographicCamera`. Also I suppose a way to get the effective frame.

2024-11-04 16:49 UTC, andy-sweet commented on src/core/renderer.ts
> +  public clientToClip(position: vec2): vec2 {
I would not expect clip-space to be 2D, so this feels like where I might provide a depth parameter to get into 3D.

2024-11-04 16:54 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +    const fov = Math.max(0.1, Math.min(179.9, this.fov_ / this.zoom_));
> I think this also means adding a "effective" width and height properties to OrthographicCamera. Also I suppose a way to get the effective frame.

Agreed. I guess the reason many libraries with cameras define zoom separately is that there's some notion of a special fixed field of view, that is temporarily zoomed in on, and to which you might want to reset to.

We might also have that, but it's likelier trickier to handle with multiple layers. Therefore, I'd be interested to try to remove zoom as a parameter and just directly mutate the width/height or fov (not necessarily in this PR though).

2024-11-04 17:45 UTC, aganders3 commented on src/core/renderer.ts
> +  public clientToClip(position: vec2): vec2 {
I agree it makes sense for clip-space to be 3D, but the input is client-space (2D). What space would the depth parameter be? Would it just be assumed to already be clip-space and passed through to a `vec3` output?

I do think it makes sense to return a `vec3`. Long-term it would make sense to use picking, but until them I'm not sure what to set it to. Some ideas:
* pass through an input
* set it to 0
* estimate from the position of the `activeCamera`

`clipToWorld` below should take in a `vec3` instead (and also return one).

2024-11-04 19:30 UTC, andy-sweet commented on src/core/renderer.ts
> +  public clientToClip(position: vec2): vec2 {
Based on the implementation this clip-space seems like OpenGL's where x/y/z are each in [-1, 1] (i.e. GL normalized device coordinates). 

So given that and  that this is a 2->3D transform, I like requiring the user to pass a clip-space value for the depth and maybe defaulting to 0 as the mid-point of [-1, 1].

Do the z=-1 and z=1 in clip-space effectively correspond to the near and far planes of the camera? Or is my understanding not quite right?

2024-11-04 21:06 UTC, aganders3 commented on src/core/renderer.ts
> +  public clientToClip(position: vec2): vec2 {
> So given that and that this is a 2->3D transform, I like requiring the user to pass a clip-space value for the depth and maybe defaulting to 0 as the mid-point of [-1, 1].

Right now this depth is passed to `clipToWorld`, which makes more sense to me, but I also don't mind moving it here. More generally I think `clientToClip` should perhaps be private (protected) but that may depend on how a `CameraControls` object works. I have some open questions about that we can discuss tomorrow.

> Do the z=-1 and z=1 in clip-space effectively correspond to the near and far planes of the camera? Or is my understanding not quite right?

I think this is correct. It's not linear between the planes in the case of the perspective camera, but I think the limits -1 and 1.

2024-11-06 20:22 UTC, aganders3 commented
I think this is ready for a look. Thanks for the comments so far.

I moved the camera controls to their own class in https://github.com/chanzuckerberg/imaging-active-learning/pull/96/commits/2f7f7e6a5d579701fed8c4bc00095cdf88136c7d but I am open to reverting that for purposes of keeping the PR a bit less intrusive. This has some oddities as we discussed yesterday, mostly due to `render.canvas` being private and the "active" camera switching.

2024-11-06 20:59 UTC, andy-sweet commented on src/renderers/shaders/projected_line_vert.glsl
> +    gl_Position = currPos + offset * currPos.w;
Is this related to the other changes this PR? Or did this PR help you debug what this is fixing?

2024-11-06 21:11 UTC, andy-sweet commented on src/core/renderer.ts
> +    if (!this.controls_) {
Optional

I'd consider inlining this and `unbindControls` to avoid the need for the error handling.

2024-11-06 21:12 UTC, andy-sweet commented on src/core/renderer.ts
> +      1 - (2 * y) / this.canvas.clientHeight,
I guess this inversion might need to be removed after merging https://github.com/chanzuckerberg/imaging-active-learning/pull/109?

I'm planning to wait to merge that after this goes in, so I can debug more easily.

2024-11-06 21:20 UTC, andy-sweet commented on examples/image2d_from_omezarr5d_u8/main.ts
> +// project the (negative) camera position to clip space
Does this need to be recalculated every time the camera position changes? Or do we assume that the z-position cannot change?

Also, could this be calculated on construction of the controls? It feels out of place in the example itself.

2024-11-06 21:24 UTC, andy-sweet commented on src/core/renderer.ts
> +    });
Should unbind also set `controlCallbacks_` to `[]`?

2024-11-06 22:05 UTC, andy-sweet commented on src/objects/cameras/controls.ts
> +    const dWorld = vec3.sub(vec3.create(), postZoomPos, preZoomPos);
Consider renaming `dWorld` to `deltaWorld` if that's what's intended.

Also consider, swapping the arguments of the subtraction here instead of scaling by -1 below.

2024-11-06 22:07 UTC, andy-sweet commented on src/objects/cameras/controls.ts
> +    console.log("mousedown", this.camera_.type);
Should these be `debug` instead of `log`?

2024-11-06 22:10 UTC, andy-sweet commented on src/objects/cameras/controls.ts
> +type ClientToClip = (clientPos: vec2, depth: number) => vec3;
Just to double check that these are the same type now, but we want to allow them to diverge in the future?

2024-11-06 22:11 UTC, andy-sweet commented on src/objects/cameras/controls.ts
> +type ClientToClip = (clientPos: vec2, depth: number) => vec3;
If not, this could be `clientTo3D` or similar?

2024-11-06 22:14 UTC, andy-sweet commented on src/objects/cameras/camera.ts
> +    const screenPos = vec4.fromValues(position[0], position[1], position[2], 1);
Why `screenPos` and not `clipPos`?

2024-11-06 22:23 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +    // clamp the field of view and zoom to prevent degenerate behavior
I also get some degenerate behavior for the orthographic camera if I zoom in far enough, though it is recoverable. Should we consider a similar clamping operation there? Although, I guess there's no way to reasonably clamp those values (other than as some multiple of the minimum absolute value of the precision).

2024-11-06 22:24 UTC, andy-sweet requested changes
Generally works and looks great, but I had enough questions and suggestions along the way, where I can't approve this quite yet. Should be able to do so soon though!

2024-11-07 14:46 UTC, aganders3 commented on src/renderers/shaders/projected_line_vert.glsl
> +    gl_Position = currPos + offset * currPos.w;
This fixes the issue raised in https://github.com/chanzuckerberg/imaging-active-learning/pull/96#discussion_r1815436015.

This PR helped debug by having multiple cameras in the same example, but it's otherwise unrelated and could be moved into a separate PR.

2024-11-07 14:49 UTC, aganders3 commented on examples/image2d_from_omezarr5d_u8/main.ts
> +// project the (negative) camera position to clip space
Yeah, I agree it's out of place here and it would needs to be recalculated if the position changed. Maybe a good solution for now would be to give `PerspectiveCamera` a `target` point and the depth can be calculated from the distance from `position` to `target`?

2024-11-07 14:51 UTC, aganders3 commented on src/objects/cameras/controls.ts
> +type ClientToClip = (clientPos: vec2, depth: number) => vec3;
I'm not sure they need to diverge. They happen to have the same signature but different meaning.

2024-11-07 14:52 UTC, aganders3 commented
> Generally works and looks great, but I had enough questions and suggestions along the way, where I can't approve this quite yet. Should be able to do so soon though!

No worries - thanks! Some good suggestions from having fresh eyes on it.

2024-11-07 14:54 UTC, aganders3 commented on src/objects/cameras/controls.ts
> +    console.log("mousedown", this.camera_.type);
Yes, or perhaps even removed.

2024-11-07 15:05 UTC, aganders3 commented on src/core/renderer.ts
> +    if (!this.controls_) {
Having them separate may be useful if we want also add `enableControls` and `disableControls`.

Another thought is to have the controls default to something like `NullControls` and avoid any error checking here. That would make `this.controls_` non-nullable, and fits with the concept of "nothing is something" in dependency injection.

2024-11-07 15:19 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +    // clamp the field of view and zoom to prevent degenerate behavior
Even with the perspective camera it's easy to lose the image if you zoom all the way out. Maybe the cameras could have configurable zoom limits somehow? I'm not sure what the best solution here is. I'll see if we can copy behavior from three.js or something.

2024-11-07 15:23 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +    // clamp the field of view and zoom to prevent degenerate behavior
We can follow up in another PR

2024-11-07 15:28 UTC, andy-sweet commented on src/core/renderer.ts
> +    if (!this.controls_) {
Enable/disable is a good point here, so I'm OK leaving as is. I also like `NullControls`, so feel free to implement that if you want.

2024-11-07 16:22 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +  private position_: vec3;
When is this used? And how is it different from `Camera.transform.translation_`?

2024-11-07 16:23 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +    // clamp the field of view and zoom to prevent degenerate behavior
For what it's worth three.js handles these limits in the controls:

https://github.com/mrdoob/three.js/blob/3728a0aafd5ee04a9a4bc66eb3f56f556bd8da15/examples/jsm/controls/OrbitControls.js#L60-L66

2024-11-07 16:25 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +  private position_: vec3;
It's used to get the clip depth in the `PanZoomControls`. It's not different from `Camera.transform.translation_`, so I can remove the property but keep the setter/getter.

2024-11-07 16:27 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +  private position_: vec3;
`Camera.transform.translation_` is currently private, but I can add a getter or use     `mat4.getTranslation(vec3.create(), this.transform.matrix)`.

2024-11-07 16:32 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +      position = vec3.create(),
Based on code inspection, I don't think `create` is guaranteed to zero out the values, so use `vec3.zero(vec3.create())` or `vec3.fromValues(0, 0, 0)` instead.

2024-11-07 16:33 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +  private position_: vec3;
Ah, I see it's in controls. But I'd still expect to be able to use `Camera.transform.translation_`.

2024-11-07 16:35 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +      position = vec3.create(),
Oh thanks - I had looked this up for `mat4` and saw it creates an identity, so I had just assumed this would make a zero vector!

2024-11-07 16:40 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +      position = vec3.create(),
Is it confusing to have `position` and `target` default to the same point? Maybe `target` should be halfway between the near and far plane or something.

2024-11-07 16:47 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +  private position_: vec3;
I agree this makes sense - just need to also override `pan` to move the target as well.

The more I'm working with this I think direct access to the camera transform could cause problems, but I am okay working that out later.

2024-11-07 16:50 UTC, andy-sweet commented on src/objects/cameras/perspective_camera.ts
> +  private target_: vec3;
`target` is state I'd expect on controls, but not on a camera. Though `Camera.lookAt` seems fine - it's the extra state that's unexpected and undesirable. I think there's something a bit off about the `PanZoomControls` for controlling a perspective camera, so I don't want to block the PR based on this. We can always follow up by implementing more suitable controls for a perspective camera (e.g. arcball, orbit).

2024-11-07 17:32 UTC, aganders3 commented on src/objects/cameras/perspective_camera.ts
> +  private target_: vec3;
> target is state I'd expect on controls, but not on a camera

This is interesting. The camera has a `position` and `direction`, but the `distance` is the part that is useful for the controls, and not for the camera itself. I'm not sure `target` is very intuitive on controls either in that case. Especially in the case of panning, where the position and target move together. I need to think about it a little more.

I agree pan/zoom may not be a very practical method for controlling a perspective camera.

2024-11-07 17:57 UTC, andy-sweet approved these changes
I'm happy enough with the state of this, so approving. I'll let you decide if you want to make some changes related to position and target.

2024-11-07 18:24 UTC, aganders3 commented
Great - I'll merge today with the knowledge there is plenty of remaining work on cameras, controls, and transforms. 😅

2024-11-07 20:08 UTC, merged